services:
  postgres:
    image: postgres:18-alpine
    container_name: svc-whitelist-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb

    volumes:
      - db:/var/lib/postgresql/data

    networks:
      shared-net:
        ipv6_address: fd98:2dd6:8f48:1d99:8164:b5f6::3
  
  app-dev:
    container_name: svc-whitelist-app-dev
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      DATABASE_URL: "[fd98:2dd6:8f48:1d99:8164:b5f6::3]:5432"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_DBNAME: "mydb"
    volumes:
      - ./app:/app:rw
    depends_on:
      - postgres
    cap_add:
      - NET_BIND_SERVICE

    networks:
      shared-net:
        ipv6_address: fd98:2dd6:8f48:1d99:8164:b5f6::2

networks:
  shared-net:
    external: true
    name: svc-net

volumes:
  db:

