FROM python:3.14-alpine

RUN --mount=type=bind,source=requirements.txt,target=requirements.txt \
  apk add --no-cache git && pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["uvicorn", "app.main:app", "--host", "::", "--port", "80", "--reload"]
