class Codes:
    # успех
    WHITELIST_CREATED_OK = "WHITELIST_CREATED_OK"
    WHITELIST_REMOVED_OK = "WHITELIST_REMOVED_OK"
    WHITELIST_CHECK_OK = "WHITELIST_CHECK_OK"

    HEALTH_OK = "HEALTH_OK"
    LIVE_OK = "LIVE_OK"

    # ошибка
    WHITELIST_ALREADY_EXISTS = "WHITELIST_ALREADY_EXISTS"
    WHITELIST_NOT_FOUND = "WHITELIST_NOT_FOUND"

    HEALTH_ERROR = "HEALTH_ERROR"